### ISSUE TITLE
Ability to select which SR's can be submitted directly without agent approval.

### ISSUE THREAD

**Issue by sabbas** [miamidade/open311#10]
Should probably be part of the configuration. The posting URL to CiRM would change.

**Comment by sabbas** [comment]
The xml configuration should contain a status submittal field. When set to a status other than 'PENDING' (default status) the API implementation should send the payload to a different URL (the one that fires all side effects).

**Comment by kamellcuba** [comment]
code completed. tested to the point of SR creation is successfully.

need to test that SRs are created triggers the side effects as expected.

@sabbas: will assign that testing task to Angel.

**Comment by kamellcuba** [comment]
@angelmartin54 please create a few SRs from front end pointing to test. make sure that you create at least couple marked as <initial_status>open</initial_status> (@nijat can assist you on finding which ones). confirm correct initial status on hub. confirm side effects took place on the ones marked as open.

**Comment by angelmartin54** [comment]
Ability to select which SR's can be submitted directly without agent approval has been tested and passed SR's specified to be open upon subtitle where open

**Comment by hilpold** [comment]
This was completed much earlier using an initial_status element in the xml configuration.
