### ISSUE TITLE
Alphabetize "All" List in App

### ISSUE THREAD

**Issue by sabbas** [miamidade/open311#12]
Please alpha sort in xml.

**Comment by kamellcuba** [comment]
if purpose of this is to be show on the ui, better do programmatically. avoid human error and easier to maintain/enhance this files.

**Comment by sabbas** [comment]
@nijat12 Agreed, please do this programmatically.

**Comment by sabbas** [comment]
Create a sort function on the client whose parameters are fed from the configuration file. Then in the configuration file add an xml section similar to the below:
<sort>
<sort-order>DESC</sort-order> 
<bottom>OTHER SR</bottom>
</sort>

**Comment by hilpold** [comment]
maybe we can do this on the server prior underneath the caching layer.

**Comment by hilpold** [comment]
After 311D app 2.7.0 controllable with xml order.
