### ISSUE TITLE
311Web/app New Alert for County park concern SR (autostart)

### ISSUE THREAD

**Issue by hilpold** [miamidade/open311#71]
![image](https://user-images.githubusercontent.com/7205800/38160370-a10e9b7a-348a-11e8-93bf-102cceaf1607.png)

Due to a bug, autostart for the app does not show the alert - only when selected from All list. In addition, for the app the link to miamidade.gov/parks was set as plain text. 

311Direct web works as expected.

Effective: 3/32 2:24AM

**Comment by lizsilva311** [comment]
Is it possible for link in Parks Webpage in the 311 Online Page open in a separate tab so that user does not lose the 311Direct page?
